---
- name: AMI frontend update
  hosts: all

  pre_tasks:
    - name: check out AMI Frontend
      git: 
        repo: "{{ amiFrontEndRepo }}"
        version: "{{ amiFrontEndBranch }}"
        dest: "{{ webRoot }}{{ amiLocalPath }}"

  roles:
    - ami-frontend-dependencies
    - ami-frontend-build