---
- name: AMI CMS
  hosts: all

  roles:
    - role: wordpress-host
      domain: '{{apiHostname}}'
      sudo: yes
    - {role: amicms-db, mode: 'install', sudo: yes}
    - {role: amicms-files, mode: 'install', sudo: yes}
    - role: amicms
      domain: '{{apiHostname}}'