---
- name: Basic AMI server setup
  hosts: all
  gather_facts: no
  sudo: yes

  roles:
    - common
    - mysql
    - postgres
    - php5-fpm
    - { role: ansible-swapfile, swapfile_size: 4GB, swapfile_swappiness: 10, swapfile_location: /mnt/swapfile }
    - role: ansible-nvm
      sudo: no
      nvm:
        version: v0.31.0
        node_version: 5.10.1