---
  - name: install php5-fpm 
    apt: name={{item}} state=installed
    with_items:
      - php5-fpm
      - php5-mysql
      - php5-cli
      - php5-gd
    register: phpinstalled


  - name: copy php.ini
    when: phpinstalled|success
    copy: src=php.ini dest=/etc/php5/fpm/php.ini mode=0644 owner=root
    notify:
    - restart php5-fpm
    - restart nginx
