## Check out Git code
- name: check out AMI Community
  git: 
    repo={{amiCommunityRepo}}
    version={{amiCommunityBranch}}
    dest={{webRoot}}{{amiCommunityLocalPath}}

- name: use node version
  shell: source ~/.profile && nvm use {{node_version}}
  args:
     executable: /bin/bash

- name: install node plugins
  shell: source ~/.profile && npm install
  args:
    executable: /bin/bash
    chdir: "{{webRoot}}{{amiCommunityLocalPath}}"

- name: Create Jurisdiction Event folder
  file: path={{webRoot}}{{amiCommunityLocalPath}}/jurisdiction_events mode=775 owner={{ unix_user }} group=www-data state=directory

- name: Copy over Jurisdiction Event config
  template: src=jurisdiction_events.json.j2 dest={{webRoot}}{{amiCommunityLocalPath}}/jurisdiction_events/jurisdiction_events.json owner={{ unix_user }} group=www-data
  sudo: yes

- name: restart amicommunity service
  service: name=amicommunity state=restarted enabled=yes
  sudo: yes